version: '2'

services:
  install:
    image: "node:7"
    volumes:
      - .:/tmp/repo
    working_dir: "/tmp/repo"
    command: bash -c "npm install && ./node_modules/.bin/bower install --allow-root"
  build:
    image: "node:7"
    volumes:
      - ..:/tmp/repo
    working_dir: "/tmp/repo/mirrorgate-docs"
    command: "npm run build"
