version: '2'

services:
  selenium:
    image: "selenium/standalone-chrome:3.0.1-aluminum"
    volumes:
      - /dev/shm:/dev/shm
  install:
      image: "node:7"
      volumes:
        - .:/tmp/repo
      working_dir: "/tmp/repo"
      command: "npm i"
  build:
      image: "node:7"
      volumes:
        - .:/tmp/repo
      working_dir: "/tmp/repo"
      command: "npm run build"
